name: Webflow Integration
on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 4 AM every day
  workflow_dispatch:  # Allows manual triggering too!

jobs:
  run-index:
      runs-on: ubuntu-latest
      environment:
      name: Webflow integration
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run main.ts file
      run: pnpm dev
      env:
        COLLECTION_ID: ${{ secrets.COLLECTION_ID }}
        WEBFLOW_API_KEY: ${{ secrets.WEBFLOW_API_KEY }}
